### ISSUE TITLE
Remake and Test all previous handlers as Config Files

### ISSUE THREAD

**Issue by chrisppy** [chrisppy/usysconf-new#2]
real world testing:

- [ ] replace current usysconf and run in chroot

- [ ] replace current usysconf and run update on new install

- [ ] replace current usysconf and run update on current install

flags:

- [x] chroot

- [x] debug

- [x] force 

- [x] live

- [x] names

- [x] norun
 
kernel:
    
- [x] apparmor

- [x] clr-boot-manager

- [x] depmod

systemd:

- [x] reexec

- [x] reload

- [x] sysusers

- [x] tmpfiles

- [x] vbox-restart

xdg:

- [x] dconf

- [x] desktop-files

- [x] fonts

- [x] gconf

- [x] glib2

- [x] gtk2_immodules

- [x] gtk3_immodules

- [x] icon-cache

- [x] mime

others:

- [x] hwdb

- [x] ldconfig

- [x] linux-driver-management

- [x] mandb

- [x] mono-certs

- [x] openssh

- [x] qol-assist

- [x] ssl

- [x] udev-rules

**Comment by DataDrake** [comment]
I just want to say thank you for continuing to work on this :) I was just taking a look to see how much progress you had made and it looks like you are off to a strong start. Cheers!

**Comment by chrisppy** [comment]
@DataDrake no problem, glad to help out

**Comment by chrisppy** [comment]
@DataDrake Sorry there has not been much progress on this lately, but I have been busy.  I should have more time soon to get back to it.

**Comment by DataDrake** [comment]
@chrisppy Don't sweat it. Life comes first.

**Comment by chrisppy** [comment]
@DataDrake I have finally had some time to get back to this.  I need to do some more testing, but I think this should be almost there.

**Comment by Jacalz** [comment]
You seem to be doing a great job with the usysconf rewrite @chrisppy. Looking forward to seeing this completed. 
I would be interested  to help out with some real world testing. Is there a good way for me help you with that perhaps?

**Comment by chrisppy** [comment]
@Jacalz I guess the best way would be to try replacing the current usysconf with this one and try and run updates on both new and current installs.  I also really need to test this out both the live medium and chroot flags to make sure that they work as expected.

**Comment by chrisppy** [comment]
The code in this repo as been moved to a pull request on https://github.com/getsolus/usysconf
